apiVersion: v1
kind: Service
metadata:
  name: odooapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8069
  selector:
    app: odooapp
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: odooapp
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: odoo.2753d5d401b64a438fd9.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: odooapp
          servicePort: 80
        path: /
